"""Fix password_hash length to 256

Revision ID: 24483d92725e
Revises: 58b2a1000868
Create Date: 2025-09-24 20:43:25.531266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24483d92725e'
down_revision = '58b2a1000868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
